apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  selector:
    app: sample-app
  ports:
  - name: sample-app-http
    protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer
status:
  loadBalancer: {}